base_url: https://diaspora.github.io/api-documentation
contribute_url: https://github.com/diaspora/api-documentation/blob/gh-pages/CONTRIBUTING.md

exclude:
  - .*
  - CONTRIBUTING.md
  - LICENSE
  - README.md

sass:
  sass_dir: assets/css
  style: nested
  deploy_style: nested

collections:
  routes:
    output: true

kramdown:
  toc_levels: 2..2

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
