url: "https://diaspora.github.io" # the base hostname & protocol
baseurl: "/api-documentation" # the subpath
contribute_url: https://github.com/diaspora/api-documentation/blob/master/CONTRIBUTING.md

exclude:
  - .*
  - CONTRIBUTING.md
  - LICENSE
  - README.md

sass:
  sass_dir: assets/css
  style: nested
  deploy_style: nested

collections:
  routes:
    output: true

kramdown:
  toc_levels: 2..2

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
